### ISSUE TITLE
Add "global" middlewares

### ISSUE THREAD

**Issue by Rysakov1986** [matthiaaas/express-file-routing#11]
How do you look at adding features like middlewares for the entire route in one place and apply all routes level below?

```php
├── routes
    ├── index.js
    └── posts
        ├── [id] // middleware or middleware1, middleware2
            ├── details.js // middleware or middleware1, middleware2
            └── index.js // middleware or middleware1, middleware2
        ├── index.js // middleware or middleware1, middleware2
        ├── middleware(s).js // ?
        └── test.js // middleware or middleware1, middleware2
    └── users
        ├── [id]
            ├── details.js
            └── index.js
        └── index.js
```

_middleware(s).js_
```js
module.exports = middleware
```
or
```js
module.exports = [
  middleware1,
  middleware2
]
```

**Comment by matthiaaas** [comment]
I think it would make more sense to put those middlewares into your main.js file before creating the file router.
What do you think?

**Comment by rhrahul** [comment]
Hi, Did you figure out how to do this? I ran into the same issue, where I want to add middleware to a group of routes to its parent, but I can't find a way to do so.

**Comment by matthiaaas** [comment]
Hey @rhrahul!

Currently, this package itself does not implement an api for declaring middlewares for something like a group of routes, because this can be easily achieved using native Express functions.

Let say you have the following routes structure:
```
├── app.js
├── routes
    ├── index.js
    ├── home.js
    └── auth
        ├── session.js
        └── signin.js
└── package.json
```

Now, you want to add a middleware that is called before every request to `/auth/*`, so for every route inside the "auth" directory.

All you have to do is add the following to your *app.js*:
```diff
// app.js
app = express()

+ app.use("/auth/*", myMiddleware)

createRouter(app)

app.listen(4000)
```

With that, `myMiddleware(req, res, next)` is called before every request to whatever route inside `/auth`.

Hope this helps. Let me know if this work for your use case.

**Comment by rhrahul** [comment]
Thank you @matthiaaas, That helps!
