### ISSUE TITLE
Invalid Request typings?

### ISSUE THREAD

**Issue by bperel** [matthiaaas/express-file-routing#22]
Apologies if this not a bug or if it's a bug that's unrelated to this project: I am not very familiar with TypeScript.

I'm trying to type the Request object, in order to spot typing errors more easily in the IDE.

This code in standard Express works:
```typescript
import express from "express";
app.get("/", (req: express.Request<{ locale: string }>) => {
  console.log(req.params.locale);
});
```

But the following using express-file-routing:
```typescript
import express from "express";
export const get: express.Handler = (req: express.Request<{ locale: string }>) => {
  console.log(req.params.locale);
};
```
gives the following error:

```TS2322: Type '(req: Request<{ locale: string;}>) => void' is not assignable to type 'Handler'.
   Types of parameters 'req' and 'req' are incompatible.
     Type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not assignable to type 'Request<{ locale: string; }, any, any, ParsedQs, Record<string, any>>'.
       Types of property 'params' are incompatible.
         Property 'locale' is missing in type 'ParamsDictionary' but required in type '{ locale: string; }'.```

Is there a workaround to make request typing work in express-file-routing?

**Comment by matthiaaas** [comment]
hey @bperel, this is an unrelated problem with this library. The issue is that your typings are redundant.

You are typing both the whole exported get function with the `express.Handler` type and the get function's req param with `express.Request`, which is already typed by the whole function type.

Try to remove either the param types or the whole function type. Let me know if this works.

**Comment by bperel** [comment]
Thank you, you were right :-)
